### PR TITLE
Fallback to heuristics if symbol ranges are not proper

### PR DESCRIPTION
**Pull request by chatziko**
Thanks for this quite useful extension. I like a lot the fact that it uses the symbol provider, instead of being bound to a single language.

However, some language servers (eg. C, Perl, Haxe) give a symbol.location.range that covers only the symbol __name__, not the __body__ of the corresponding class/function/etc. Such ranges are useless for the purposes of this extension, so we get "Global Scope" everywhere.

This PR detects "proper" ranges by checking whether all symbols cover just a single line. If we don't have proper ranges we fallback to heuristics:
- check nestedness based on the symbol kind (eg classes contain functions but not other classes).
- assume that a symbol extends either until the start of its next sibling (if any) or unti the end of its parent.

These are not 100% accurate (eg in the space between two functions we still believe that we're inside the function), but seems to work well in practice and is way better than nothing anyway.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
This seems to be happening for me in C#--I only see the method name in the Scope Bar if my cursor is on the method name, which is of course not the most useful thing. Any concerns about this approach @amos402?

**Comment by amos402** [comment]
Oh, I notice this PR notification before, sorry about that. :(
I will check it as soon as possible.

**Comment by amos402** [comment]
Yes, C# extension did't provide the scope ending for a function, this feature can fix it.
But it has just a little imperfect thing, the calculate of scope ending will extend ouside and end before next function. You should know that. I will upload a new version package latter. @RikkiGibson 
Thanks @chatziko for provide this feature.

**Comment by jens1o** [comment]
@amos402 Could you file a new release please?

**Comment by amos402** [comment]
@jens1o Yes, you should upgrade it from extension market for now.

**Comment by jens1o** [comment]
Thank you!

**Comment by RikkiGibson** [comment]
Good to know. Thank you for your work on this extension! @amos402 @chatziko

**Pull request merged**
